# Generated by Django 3.1.7 on 2021-03-28 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comment'),
        ('articles', '0002_article_user'),
    ]

    operations = [
    ]
